STATUS = "status"
RUNNING = "Running"
NOT_RUNNING = "Not Running"
NO_RESPONSE = "No Response"
ENABLE = "enable"
START = "start"
STOP = "stop"
OFF = "Off"
ON = "On"
NA = "Unknown"
INIT = "init"
NODE_LIST = "node_list"
SUB_TEMPLATE = "sub_template"


# Collectd Constants
CollectdPluginDestDir = '/opt/collectd'
CollectdPluginConfDir = '/opt/collectd'
CollectdConfDir = '/opt/collectd/etc'

# Collector - constants.py
COLLECTORS = "collectors"
COLLECTOR_MGR = "collector_manager"
COLLECTD_MGR = "collectd_manager"
NODEMGR = "nodemgr_type"
ERROR = "error_msg"
ENABLED = "enable"
NODES = "nodelist"
TAGS = "tags"
TARGETS = "targets"
CONFIG = "config"
FAILED_LIST = "failed_list"
SUCCESS_LIST = "success_list"
SALT = "salt"
COLLECTD = "collectd"
COLLECTOR = "collector_type"
ALL_CONF = "/*.conf"
DELETE = "delete"
FILTERS = "filters"
PLUGIN = "Plugin"
OPTIONS = "Options"
EXTSN = ".conf"
TEMPLATE_DIR = "orchestrator/collector/templates"
INTERVAL = "interval"
NAME = "name"
PLUGINS = "plugins"
ELASTICSEARCH = "elasticsearch"
HOST = "host"
PORT = "port"
INDEX = "index"
SERVER_IP = "server_ip"
SERVER_PORT = "server_port"
CLIENT_IP = "client_ip"
CLIENT_PORT = "client_port"
TYPE = "type"
NODE_NAME = "node_name"
NO_RESP = "No Response"
RUNNING = "Running"
NOT_RUNNING = "Not Running"

# operations
START = "start"
STOP = "stop"
RESTART = "restart"
STATUS = "status"
PUSH = "push"

# ERROR MESSAGES
EMPTY_NODE_LIST = "No nodes specified"
KEY_ERROR = " key not found"
ERROR_CFG_GEN = "Configuration generation failed"
DUMMY = "dummy"
