# Worker type
READER = "reader"
WRITER = "writer"

# cmd keys
CMD = "cmd"
CNTRL = "cntrl"
META = "meta"
DEST_LIST = "dest_list"
TARGET = "plugin_file"
MSG_TYPE = "msg_type"
RECOVER = "recover"
START = "start"
STOP = "stop"
STOPALL = "stopall"
STATE = "state"
UPDATE = "update"
RESUME = "resume"
TEARDOWN = "teardown"
TEARDOWNALL = "teardownall"
CHECK_POINT = "check_point"
CNTRL_DATA_MAP = "cntrl_data_map"
PLUGIN_TYPE = "plugin_type"
PLUGIN_ID = "plugin_id"
TAG = "tags"
INTERVAL = "interval"
RUN_COUNT = "run_count"

# default interval
DEFAULT_INTERVAL = 10
