from loggers.orchestrator.collector.conf import *

COLLECTORS = "collectors"
NODEMGR = "nodemgr_type"
ERROR = "error_msg"
ENABLED = "enabled"
NODES = "node_list"
TAGS = "tags"
TARGETS = "targets"
CONFIG = "config"
FAILED_LIST = "failed_list"
SUCCESS_LIST = "success_list"
SALT = "salt"
COLLECTD = "collectd"
COLLECTOR = "collector_type"
ALL_CONF = CollectdPluginDestDir + "/*.conf"
DELETE = "delete"
FILTERS = "filters"
PLUGIN = "Plugin"
OPTIONS = "Options"
EXTSN = ".conf"
TEMPLATE_DIR = "orchestrator/collector/templates"
INTERVAL = "interval"
NAME = "name"
PLUGINS = "plugins"
ELASTICSEARCH = "elasticsearch"
HOST = "host"
PORT = "port"
INDEX = "index"
SERVER_IP = "server_ip"
SERVER_PORT = "server_port"
CLIENT_IP = "client_ip"
CLIENT_PORT = "client_port"
TYPE = "type"

# operations
START = "start"
STOP = "stop"
RESTART = "restart"
STATUS = "status"
PUSH = "push"

# ERROR MESSAGES
EMPTY_NODE_LIST = "No nodes specified"
KEY_ERROR = " key not found"
ERROR_CFG_GEN = "Configuration generation failed"
DUMMY = "dummy"
